run:
  tests: true

linters:
  enable:
#    - wsl
#    - nlreturn
#    - wrapcheck
#    - revive

    - containedctx
    - contextcheck
    - bodyclose
    - stylecheck
    - sqlclosecheck
    - gocritic
    - errcheck
    - govet
    - staticcheck
    - gofmt
    - gosec
    - gomnd
    - whitespace
    - wastedassign
    - dupl
    - dupword
    - errname
    - errorlint
    - gocyclo
    - errchkjson
    - nonamedreturns
    - paralleltest
    - goerr113

linters-settings:
  govet:
    disable:
      - printf
  stylecheck:
    checks: ["all", "-ST1001", "-ST1003"]
  gosec:
    excludes:
      - G404 # Use of weak random number generator
      - G107 # Potential HTTP request made with variable url
      - G306 # Expect WriteFile permissions to be 0600 or less
