bind:
  http: :7778
  udp: :7776
oauth:
  github:
    org: ""
    client_id: Iv1.593fb37918638852
    client_secret: 04d48fe9e27e65d17fbc82b61502dcf9ef58be71
  jwt_secret: bb41f446610565543d0b67f7
clickhouse: tcp://clickhouse-server:9000?database=logrdb&username=logr&password=12345678
mysql: logr:12345678@tcp(mysql:3306)/logrdb
allow_no_cipher: false
