version: '2.4'

volumes:
  clickhouse-volume:
  mysql-volume:

services:
  templator:
    image: bash
    working_dir: /opt/logr
    healthcheck:
      test: ps -o comm | grep -q templator && exit 1 || exit 0
      interval: 1s
      timeout: 2s
      retries: 600
    volumes:
      - ./:/opt/logr
    command: bash -c "templates/templator.sh && sleep 5"

  clickhouse-server:
    image: yandex/clickhouse-server
    depends_on:
      templator:
        condition: service_started
    volumes:
      - clickhouse-volume:/var/lib/clickhouse
      - ./${CLICKHOUSE_USER}.xml:/etc/clickhouse-server/users.d/${CLICKHOUSE_USER}.xml

  clickhouse-client:
    image: yandex/clickhouse-server
    depends_on:
      clickhouse-server:
        condition: service_started
    command: ['clickhouse-client','--host', 'clickhouse-server', '-q CREATE DATABASE IF NOT EXISTS ${CLICKHOUSE_DATABASE}']

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  logr:
    build: .
    ports:
      - "127.0.0.1:7778:7778"
    working_dir: /opt/logr
    restart: always
    volumes:
      - ./:/opt/logr
    command: --config="./config.docker.yml"
