version: '2.4'

volumes:
  clickhouse-volume:
  mysql-volume:

services:
  clickhouse:
    image: yandex/clickhouse-server
    ulimits:
      nofile:
        soft: "262144"
        hard: "262144"
    volumes:
      - clickhouse-volume:/var/lib/clickhouse
      - ./clickhouse/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./clickhouse/${CLICKHOUSE_USER}.xml:/etc/clickhouse-server/users.d/${CLICKHOUSE_USER}.xml

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  server:
    build: .
    ports:
      - "7778:7778"
      - "7776:7776"
    working_dir: /opt/logr
    restart: always
    links:
      - clickhouse
      - mysql
    volumes:
      - ./config.yml:/opt/logr/config.yml
    command: --config="./config.yml"
