version: '2.4'

volumes:
  clickhouse-volume:
  mysql-volume:

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.12
    container_name: "clickhouse_logr"
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DATABASE}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse-volume:/var/lib/clickhouse

  mysql:
    image: mysql:5.7
    container_name: "mysql_logr"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  server:
    container_name: "logr"
    build: .
    ports:
      - "7778:7778"
      - "7776:7776"
    working_dir: /opt/logr
    restart: always
    links:
      - clickhouse
      - mysql
    volumes:
      - ./config.yml:/opt/logr/config.yml
    command: --config="./config.yml"
