name: "Deploy"

on:
  push:
    tags:
      - '*'

env:
  IMAGE_NAME: "kozhurkin/logr"
  CONTAINER_NAME: "logr-container"

jobs:
  image-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tag with submodules
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}
          submodules: recursive

      - name: Show commit information
        run: |
          echo "Main repo commit: $(git rev-parse HEAD)"
          git submodule foreach 'echo "Submodule $name commit: $(git rev-parse HEAD)"'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          pwd
          ls -lah
          docker buildx create --use
          docker buildx build ./ --no-cache --push --platform linux/amd64,linux/arm64 -t $IMAGE_NAME:${{ github.ref_name }} -f ./Dockerhub/Dockerfile