name: "Deploy"

on:
  push:
    tags:
      - '*'

env:
  IMAGE_NAME: "kozhurkin/logr"
  DEPLOY_DIRECTORY: "/home/logr/logr"
  CONTAINER_NAME: "logr-container"


jobs:
  image-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tag with submodules
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}
          submodules: recursive

      - name: Show commit information
        run: |
          echo "Main repo commit: $(git rev-parse HEAD)"
          git submodule foreach 'echo "Submodule $name commit: $(git rev-parse HEAD)"'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build ./ --no-cache --push -t $IMAGE_NAME:${{ github.ref_name }} -f ./Dockerhub/Dockerfile --platform linux/amd64,linux/arm64

  deploy-image:
    runs-on: ubuntu-latest
    needs: image-build-and-push
    steps:
      - name: Deploy image via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          envs: CONTAINER_NAME,IMAGE_NAME
          script: |
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker stop $CONTAINER_NAME || true
            sudo docker rm $CONTAINER_NAME || true
            sudo docker run -d -p 7776:7776/udp -p 7778:7778 --name $CONTAINER_NAME $IMAGE_NAME:${{ github.ref_name }}